version: '3.8'
services:

  mysql_db:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      # - MYSQL_HOST=$MYSQL_LOCAL_HOST
      # - MYSQL_USER=$MYSQL_USER
      # - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3

  app:
    container_name: rolling
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql_db:
        condition: service_healthy
    links:
      - mysql_db

    image: rolling_dices
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQL_HOST=$MYSQL_DOCKER_HOST
      - MYSQL_USER= $MYSQL_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

volumes:
  mysql-data: